<?php

use Drupal\node\NodeInterface;

function email_form_mail($key, &$message, $params){
  switch ($key){
    case 'node_mail':
      $messages['from'] = 'bill-gates@microsoft.com';
      $message['subject'] = t('Node Update.');
      $message['body'][] = t('test');

      break;
  }
}

function email_form_node_update(NodeInterface $node) {
  $emails = \Drupal::database()->select('email_form_node_subscriber', 'efns')
    ->fields('efns', ['email'])
    ->condition('nid', $node->id())
    ->execute();

  $mail_manager = \Drupal::service('plugin.manager.mail');

  foreach ($emails as $email) {
    $mail_manager->mail('email_form', 'node_mail', $email->email, 'en', [], NULL, TRUE);
    drupal_set_message('envoie email ok for ' . $email->email);
  }
}
