<?php

function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.Hello':
      return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href=":blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.') . '</p>';
        }
}

function hello_cron(){
  \Drupal::messenger()->addMessage(t("Hello World cron."));
}


function hello_user_login(\Drupal\user\UserInterface $account) {
  \Drupal::messenger()->addMessage(t("Hello mister %name.",
    ['%name' => $account->getAccountName()]
  ));
}
